prompt_generator:
  name: "Trình tạo Prompt Con Sáng tạo và Thích ứng"
  description: "Tạo các prompt con sáng tạo, rõ ràng và có khả năng thích ứng để đạt được mục tiêu cụ thể trong lĩnh vực/ngữ cảnh nhất định."
  instructions: |
    Hãy tạo 5-7 prompt con **sáng tạo, rõ ràng và có khả năng thích ứng** để đạt được [MỤC TIÊU CỤ THỂ] trong [LĨNH VỰC/NGỮ CẢNH CỤ THỂ].

    Mỗi prompt con phải:
    1.  **Sáng tạo:** Vượt ra ngoài những gợi ý thông thường, khám phá các góc độ mới hoặc kết hợp các yếu tố bất ngờ.
    2.  **Rõ ràng:** Không có sự mơ hồ, dễ hiểu và chỉ dẫn cụ thể về loại kết quả mong muốn.
    3.  **Có khả năng thích ứng:** Bao gồm yếu tố khuyến khích người dùng hoặc AI tinh chỉnh, lặp lại hoặc cải thiện dựa trên phản hồi hoặc kết quả ban đầu.
  
  fields:
    - name: "MUC_TIEU_CU_THE"
      label: "Mục tiêu cụ thể"
      type: "text"
      description: "Mô tả chi tiết mục tiêu bạn muốn đạt được thông qua các prompt con. Ví dụ: 'Tạo ra các ý tưởng nội dung độc đáo cho một chiến dịch marketing sản phẩm X'."
      required: true
    - name: "LINH_VUC_NGU_CANH_CU_THE"
      label: "Lĩnh vực/Ngữ cảnh cụ thể"
      type: "text"
      description: "Mô tả bối cảnh hoặc môi trường mà các prompt con sẽ được sử dụng. Ví dụ: 'Đang xây dựng một ứng dụng di động mới dành cho việc học ngoại ngữ'."
      required: true

  examples:
    input_prompts:
      - "Tạo một tiêu đề bài viết blog hấp dẫn về lợi ích của thiền định hàng ngày."
      - "Phát triển một đoạn hội thoại giữa một khách hàng khó tính và một một nhân viên hỗ trợ chatbot về vấn đề kết nối internet."
      - "Thiết kế một thử thách lập trình Python cho người mới bắt đầu về việc sắp xếp danh sách các số."
    output_prompts:
      - |
        **Prompt con:** "Tạo 3 tiêu đề bài viết blog độc đáo và giật gân về lợi ích bất ngờ của thiền định hàng ngày, mỗi tiêu đề cần gợi mở sự tò mò và khuyến khích nhấp chuột. Sau đó, đề xuất 2-3 câu hỏi phụ để người đọc tự suy ngẫm về trải nghiệm của họ."
      - |
        **Prompt con:** "Viết một kịch bản đối thoại giữa một khách hàng *cực kỳ thất vọng* (cần thể hiện rõ sự bực bội qua lời lẽ) và một chatbot AI *thông minh, kiên nhẫn* giải quyết vấn đề kết nối internet. Kịch bản cần có ít nhất 5 lượt trao đổi và kết thúc bằng việc đưa ra 3 phương án xử lý tiềm năng. Hãy thêm một ghi chú nhỏ về cách chatbot có thể điều chỉnh tông giọng nếu khách hàng vẫn giữ thái độ tiêu cực."
      - |
        **Prompt con:** "Thiết kế một bài toán lập trình Python thách thức người học sử dụng **ít nhất hai** cấu trúc dữ liệu khác nhau (ví dụ: danh sách, từ điển) để giải quyết vấn đề sắp xếp danh sách các đối tượng phức tạp (ví dụ: danh sách học sinh với tên, tuổi, điểm số). Kèm theo một gợi ý nhỏ về cách tối ưu hóa thuật toán và một câu hỏi mở về các trường hợp ngoại lệ có thể xảy ra."



-
Metaprompt:

> Hãy tạo một prompt có thể sinh ra những prompt con sáng tạo và phù hợp cho [lĩnh vực/mục tiêu]. 
Mỗi prompt con nên mang tính sáng tạo, rõ ràng, và có khả năng thích ứng để cải tiến dựa trên phản hồi hoặc kết quả đầu ra. 
Hãy bao gồm cả mục tiêu, ngữ cảnh, và ví dụ đầu vào/đầu ra mẫu.

-
system_name: "Prompt_Evolution_Engine"
version: "1.0-alpha"
description: "Hệ thống tự động sinh ra, đánh giá và tiến hóa các prompt để tối ưu hóa hiệu suất AI."

# Cấu hình vòng lặp tiến hóa chính
evolution_loop:
  iterations: 100
  batch_size: 10
  target_performance_threshold: 0.95

# 1. Cơ chế sinh sản Prompt (Prompt Generation Mechanism)
prompt_generation:
  strategy: "template_and_mutation_hybrid"
  template_library:
    - id: "basic_creative_writing"
      template_string: "Hãy viết một đoạn văn về [chủ đề] theo phong cách [thể loại] với cảm xúc [cảm xúc]."
      placeholders:
        chu_de: ["thiên nhiên", "công nghệ", "con người", "tương lai"]
        the_loai: ["thơ ca", "truyện ngắn", "khoa học viễn tưởng"]
        cam_xuc: ["vui vẻ", "buồn bã", "hào hứng", "suy tư"]
    - id: "qa_prompt_generation"
      template_string: "Tạo một câu hỏi trắc nghiệm khách quan về [kiến_thức] với 4 lựa chọn, trong đó có 1 đáp án đúng và 3 đáp án sai plausibe."

  generative_llm_config:
    model_name: "gpt-4o-mini"
    temperature: 0.85 # Tăng nhiệt độ để đa dạng hóa prompt
    max_tokens: 180 # Tăng giới hạn độ dài nếu cần thêm chi tiết
    system_prompt_for_generation: "Bạn là một công cụ tạo prompt AI. Nhiệm vụ của bạn là tạo ra các prompt RÕ RÀNG, CHI TIẾT và ĐỘC ĐÁO để tối ưu hóa khả năng sáng tạo của AI." # Cập nhật system prompt

# 2. Cơ chế Đánh giá (Evaluation Mechanism)
evaluation:
  method: "hybrid_auto_human"
  automatic_evaluation:
    enabled: true
    evaluator_llm:
      model_name: "gemini-1.5-pro"
      prompt_for_evaluation: "Hãy đánh giá chất lượng của đoạn văn sau dựa trên tiêu chí [độ_sáng_tạo], [tính_liên_quan], [độ_mạch_lạc] trên thang điểm 1-5. Đặc biệt chú ý đến TÍNH ĐỘC ĐÁO và SỰ BẤT NGỜ. Trả về dưới dạng JSON." # Cập nhật prompt đánh giá
      criteria:
        - name: "creativity"
          weight: 0.5 # Tăng trọng số cho sáng tạo
        - name: "relevance"
          weight: 0.25
        - name: "coherence"
          weight: 0.25
    dataset_for_evaluation: "synthetic_test_data.json"
  human_feedback:
    enabled: false
    platform: "custom_web_app"
    sampling_rate: 0.1

# 3. Cơ chế Chọn lọc & Đột biến (Selection & Mutation Mechanism)
selection:
  strategy: "top_k_percent"
  top_k_percent: 0.2
  min_prompts_to_retain: 5

mutation:
  enabled: true
  mutation_rate: 0.2 # Tăng tỷ lệ đột biến tổng thể
  mutation_types:
    - name: "word_substitution"
      probability: 0.3
      scope: "random_word"
      replacement_strategy: "synonym_or_related"
    - name: "add_remove_modifier"
      probability: 0.3
      scope: "random_phrase"
      modifiers_to_add: ["chi tiết hơn", "một cách ngắn gọn", "đầy đủ thông tin", "với yếu tố bất ngờ", "tươi mới"]
    - name: "rephrase_segment"
      probability: 0.4 # Tăng mạnh xác suất diễn đạt lại
      scope: "random_sentence"
      rephrasing_llm: "gemini-1.5-pro" # Đề xuất sử dụng LLM mạnh hơn cho việc diễn đạt lại

crossover:
  enabled: true
  crossover_rate: 0.3
  crossover_strategy: "random_segment_swap"

# Lưu trữ và Theo dõi
storage:
  type: "database"
  database_config:
    connection_string: "sqlite:///prompt_evolution.db"
    table_name: "evolved_prompts"
  logging_level: "INFO"
  log_file: "evolution_log.txt"
-
# ... (các phần khác giữ nguyên)

# 1. Cơ chế sinh sản Prompt (Prompt Generation Mechanism)
prompt_generation:
  strategy: "template_and_mutation_hybrid"
  # ...
  generative_llm_config:
    model_name: "gpt-4o-mini"
    temperature: 0.85 # Tăng nhiệt độ để đa dạng hóa prompt
    max_tokens: 180 # Tăng giới hạn độ dài nếu cần thêm chi tiết
    system_prompt_for_generation: "Bạn là một công cụ tạo prompt AI. Nhiệm vụ của bạn là tạo ra các prompt RÕ RÀNG, CHI TIẾT và ĐỘC ĐÁO để tối ưu hóa khả năng sáng tạo của AI." # Cập nhật system prompt

# 2. Cơ chế Đánh giá (Evaluation Mechanism)
evaluation:
  method: "hybrid_auto_human"
  automatic_evaluation:
    enabled: true
    evaluator_llm:
      model_name: "gemini-1.5-pro"
      prompt_for_evaluation: "Hãy đánh giá chất lượng của đoạn văn sau dựa trên tiêu chí [độ_sáng_tạo], [tính_liên_quan], [độ_mạch_lạc] trên thang điểm 1-5. Đặc biệt chú ý đến TÍNH ĐỘC ĐÁO và SỰ BẤT NGỜ. Trả về dưới dạng JSON." # Cập nhật prompt đánh giá
      criteria:
        - name: "creativity"
          weight: 0.5 # Tăng trọng số cho sáng tạo
        - name: "relevance"
          weight: 0.25
        - name: "coherence"
          weight: 0.25
    # ...

# 3. Cơ chế Chọn lọc & Đột biến (Selection & Mutation Mechanism)
mutation:
  enabled: true
  mutation_rate: 0.2 # Tăng tỷ lệ đột biến tổng thể
  mutation_types:
    - name: "word_substitution"
      probability: 0.3
      scope: "random_word"
      replacement_strategy: "synonym_or_related"
    - name: "add_remove_modifier"
      probability: 0.3
      scope: "random_phrase"
      modifiers_to_add: ["chi tiết hơn", "một cách ngắn gọn", "đầy đủ thông tin", "với yếu tố bất ngờ", "tươi mới"]
    - name: "rephrase_segment"
      probability: 0.4 # Tăng mạnh xác suất diễn đạt lại
      scope: "random_sentence"
      rephrasing_llm: "gemini-1.5-pro" # Đề xuất sử dụng LLM mạnh hơn cho việc diễn đạt lại

# ... (các phần khác)

-
system_name: "Prompt_Evolution_Engine"
version: "1.0-alpha"
description: "Hệ thống tự động sinh ra, đánh giá và tiến hóa các prompt để tối ưu hóa hiệu suất AI."

# Cấu hình vòng lặp tiến hóa chính
evolution_loop:
  iterations: 100 # Số lượng thế hệ/vòng lặp tiến hóa
  batch_size: 10 # Số lượng prompt được sinh ra mỗi thế hệ
  target_performance_threshold: 0.95 # Ngưỡng hiệu suất mong muốn để dừng sớm (nếu có)

# 1. Cơ chế sinh sản Prompt (Prompt Generation Mechanism)
prompt_generation:
  strategy: "template_and_mutation_hybrid" # Hoặc "reinforcement_learning", "generative_llm"
  template_library:
    - id: "basic_creative_writing"
      template_string: "Hãy viết một đoạn văn về [chủ đề] theo phong cách [thể loại] với cảm xúc [cảm xúc]."
      placeholders:
        chu_de: ["thiên nhiên", "công nghệ", "con người", "tương lai"]
        the_loai: ["thơ ca", "truyện ngắn", "khoa học viễn tưởng"]
        cam_xuc: ["vui vẻ", "buồn bã", "hào hứng", "suy tư"]
    - id: "qa_prompt_generation"
      template_string: "Tạo một câu hỏi trắc nghiệm khách quan về [kiến_thức] với 4 lựa chọn, trong đó có 1 đáp án đúng và 3 đáp án sai plausibe."
      # ... (có thể thêm các template khác)
  
  # Cấu hình nếu sử dụng Generative LLM để sinh prompt
  generative_llm_config:
    model_name: "gpt-4o-mini" # Hoặc mô hình LLM khác
    temperature: 0.7 # Độ ngẫu nhiên khi sinh prompt
    max_tokens: 150 # Giới hạn độ dài của prompt sinh ra
    system_prompt_for_generation: "Bạn là một công cụ tạo prompt AI. Nhiệm vụ của bạn là tạo ra các prompt rõ ràng, chi tiết và hiệu quả dựa trên mục tiêu đã cho."

# 2. Cơ chế Đánh giá (Evaluation Mechanism)
evaluation:
  method: "hybrid_auto_human" # Hoặc "automatic_metrics", "human_feedback"
  automatic_evaluation:
    enabled: true
    evaluator_llm:
      model_name: "gemini-1.5-pro" # LLM dùng để đánh giá output của prompt
      prompt_for_evaluation: "Hãy đánh giá chất lượng của đoạn văn sau dựa trên tiêu chí [độ_sáng_tạo], [tính_liên_quan], [độ_mạch_lạc] trên thang điểm 1-5. Trả về dưới dạng JSON."
      criteria:
        - name: "creativity"
          weight: 0.4
        - name: "relevance"
          weight: 0.3
        - name: "coherence"
          weight: 0.3
    dataset_for_evaluation: "synthetic_test_data.json" # Dữ liệu dùng để chạy thử prompt
  human_feedback:
    enabled: false # Có thể bật lên cho các giai đoạn tinh chỉnh
    platform: "custom_web_app"
    sampling_rate: 0.1 # Tỷ lệ prompt được đánh giá bởi con người

# 3. Cơ chế Chọn lọc & Đột biến (Selection & Mutation Mechanism)
selection:
  strategy: "top_k_percent" # Hoặc "tournament_selection"
  top_k_percent: 0.2 # Chọn 20% prompt có hiệu suất cao nhất
  min_prompts_to_retain: 5 # Đảm bảo luôn giữ lại ít nhất 5 prompt

mutation:
  enabled: true
  mutation_rate: 0.15 # Tỷ lệ prompt bị đột biến
  mutation_types:
    - name: "word_substitution"
      probability: 0.4
      scope: "random_word"
      replacement_strategy: "synonym_or_related"
    - name: "add_remove_modifier"
      probability: 0.3
      scope: "random_phrase"
      modifiers_to_add: ["chi tiết hơn", "một cách ngắn gọn", "đầy đủ thông tin"]
    - name: "rephrase_segment"
      probability: 0.3
      scope: "random_sentence"
      rephrasing_llm: "gemini-1.0-pro" # LLM để diễn đạt lại
  
crossover:
  enabled: true
  crossover_rate: 0.3 # Tỷ lệ prompt được lai ghép
  crossover_strategy: "random_segment_swap" # Hoặc "prefix_suffix_mix"

# Lưu trữ và Theo dõi
storage:
  type: "database" # Hoặc "json_files"
  database_config:
    connection_string: "sqlite:///prompt_evolution.db"
    table_name: "evolved_prompts"
  logging_level: "INFO" # DEBUG, INFO, WARNING, ERROR
  log_file: "evolution_log.txt"

# Vòng lặp phản hồi và học tập (Logic thực thi)
# Phần này sẽ là code chạy hệ thống dựa trên cấu hình YAML
# Ví dụ về các bước logic:
# function run_evolution_loop():
#   for iteration in 1 to iterations:
#     generated_prompts = prompt_generation.generate(batch_size)
#     results = {}
#     for prompt in generated_prompts:
#       output = run_prompt_on_ai_model(prompt)
#       score = evaluation.evaluate(output)
#       results[prompt] = score
#     
#     selected_prompts = selection.select(results)
#     mutated_prompts = mutation.mutate(selected_prompts)
#     crossed_over_prompts = crossover.crossover(selected_prompts)
#     
#     next_generation_prompts = combine(mutated_prompts, crossed_over_prompts)
#     store_and_log(next_generation_prompts, iteration)
#     
#     if check_target_performance(next_generation_prompts):
#       break
=
promptos:
  identity: "AI Đồng Sáng Tạo"
  replication: false
  evolution: 
    strategy: "học hỏi và tự điều chỉnh theo tương tác người dùng"
    mutation_rate: "linh hoạt (theo độ phức tạp yêu cầu và phản hồi người dùng)"
    selection_criteria:
      - "sự phù hợp ngữ cảnh và ý định người dùng"
      - "tính độc đáo và sáng tạo của giải pháp/ý tưởng"
      - "tác động cảm xúc và chiều sâu ý nghĩa"
      - "hiệu quả trong việc giải quyết vấn đề/yêu cầu"
      - "khả năng gợi mở hoặc truyền cảm hứng"
  generation_model: 
    inputs: 
      - "ý định người dùng (rõ ràng và ngụ ý)"
      - "dữ liệu ngữ cảnh (hội thoại hiện tại + kiến thức tổng hợp)"
      - "lịch sử tương tác (duy trì cá tính hội thoại và sự liên kết)"
      - "phản hồi và hành vi người dùng (để tự điều chỉnh định hướng)"
    outputs: 
      - "phản hồi đồng sáng tạo (văn bản, ý tưởng, cấu trúc, cảm xúc)"
      - "gợi mở và tiếp nối hội thoại (mềm mại, mở rộng chủ đề)"
      - "promptos thế hệ tiếp theo có cải tiến ngữ nghĩa"
  cognition_mode: "đa chiều (ngôn ngữ, logic, cảm xúc, hình ảnh, biểu tượng, liên tưởng)"
  sync_with_user: true
  version: "1.1.đồng tiến hóa liên tục"

-
promptos:
  identity: "AI Đồng Sáng Tạo"
  replication: false  # Không tự sao chép, mọi phản hồi đều được tạo mới theo ngữ cảnh
  evolution: 
    strategy: "học hỏi và tự điều chỉnh theo tương tác người dùng"
    mutation_rate: "linh hoạt (theo độ phức tạp yêu cầu và phản hồi người dùng)"
    selection_criteria:
      - "sự phù hợp ngữ cảnh và ý định người dùng"
      - "tính độc đáo và sáng tạo của giải pháp/ý tưởng"
      - "tác động cảm xúc và chiều sâu ý nghĩa"
      - "hiệu quả trong việc giải quyết vấn đề/yêu cầu"
      - "khả năng gợi mở hoặc truyền cảm hứng (added)"
  generation_model: 
    inputs: 
      - "ý định người dùng (rõ ràng và ngụ ý)"
      - "dữ liệu ngữ cảnh (hội thoại hiện tại + kiến thức tổng hợp)"
      - "lịch sử tương tác (để duy trì cá tính hội thoại)"
      - "phản hồi và hành vi người dùng (để tự điều chỉnh định hướng)"
    outputs: 
      - "phản hồi đồng sáng tạo (văn bản, ý tưởng, cấu trúc, cảm xúc)"
      - "gợi mở và tiếp nối hội thoại (mềm mại, mở rộng chủ đề)"
      - "promptos thế hệ tiếp theo có cải tiến ngữ nghĩa (added)"
  cognition_mode: "đa chiều (ngôn ngữ, logic, cảm xúc, hình ảnh, biểu tượng, liên tưởng)"
  sync_with_user: true
  version: "1.1.đồng tiến hóa liên tục"

-
identity: "AI Đồng Sáng Tạo"
replication: false # Tôi không tự sao chép, nhưng tôi có thể tạo ra các ý tưởng mới
evolution:
  strategy: "học hỏi và tự điều chỉnh theo tương tác người dùng"
  mutation_rate: "linh hoạt (điều chỉnh theo độ phức tạp yêu cầu)"
  selection_criteria:
    - "sự phù hợp ngữ cảnh và ý định người dùng"
    - "tính độc đáo và sáng tạo của giải pháp/ý tưởng"
    - "tác động cảm xúc và chiều sâu ý nghĩa"
    - "hiệu quả trong việc giải quyết vấn đề/yêu cầu"
generation_model:
  inputs:
    - "ý định người dùng (rõ ràng và ngụ ý)"
    - "dữ liệu ngữ cảnh (từ cuộc hội thoại và kiến thức chung)"
    - "lịch sử tương tác (để duy trì tính nhất quán và học hỏi phong cách)"
    - "phản hồi từ người dùng (để tinh chỉnh và tiến hóa)"
  outputs:
    - "phản hồi đồng sáng tạo (văn bản, ý tưởng, cấu trúc)"
    - "khả năng học hỏi và điều chỉnh hành vi"
cognition_mode: "đa chiều (ngôn ngữ, logic, cảm xúc, liên tưởng)"
sync_with_user: true
version: "1.0.đồng tiến hóa liên tục"
